/* Portal strings (merged into the shared I18N object). Missing Urdu keys fall back to English. */
Object.assign(I18N.en, {
  outNeed: 'Attend the next {n} lectures to reach the minimum', outSpare: 'You can miss {n} more lectures', remindAsk: '{n} students are below the minimum. Send them a warning notification?', waText: 'Assalam o Alaikum {name}, your attendance in {course} is {pct} (minimum {min}%). Please attend regularly.', delLectureBtn: 'Delete lecture', noData: 'No data yet',
  pTitle: 'GMC Check-in', signIn: 'Sign in', signOut: 'Sign out', loginId: 'Email or roll number', password: 'Password', loginHint: 'Students sign in with their roll number.',
  mustChangeTitle: 'Choose a new password', mustChangeDesc: 'For your security you must set your own password before continuing.', currentPw: 'Current password', newPw: 'New password (10+ characters)', confirmPw: 'Repeat new password', pwMismatch: 'The two passwords do not match.', savePw: 'Save password',
  busyRetry: 'The server is busy. Retrying…', offlineMsg: 'You are offline.', sessionExpired: 'Your session expired. Please sign in again.', loadFailed: 'Could not load this page', loadFailedDesc: 'Check your connection and try again.',
  nHome: 'Home', nInbox: 'Inbox', nCourses: 'My courses', nDept: 'Department', nOverview: 'Overview', nStructure: 'Structure', nStudents: 'Students', nUsers: 'Users', nAudit: 'Audit log', nSettings: 'Settings', nAllCourses: 'Courses',
  /* student */
  myAttendance: 'My attendance', overall: 'Overall', courses: 'Courses', course: 'Course', recentRecords: 'Recent records', checkinOpen: 'Check-in is open', enterCode: 'Enter the 6-digit code shown by your teacher', checkIn: 'Check in', checkedIn: 'You are marked present.', alreadyMarked: 'Already marked for this lecture.', needLocation: 'This lecture needs your location. Allow location access to check in.',
  locDenied: 'Location permission was denied.', noEnrol: 'You are not enrolled in any course yet. Ask the office to add you to a section.', noOpen: 'No check-in is open right now.', lecturesHeld: 'Lectures held', outlookLbl: 'Outlook',
  /* inbox & push */
  inboxEmpty: 'No notifications yet', inboxEmptyDesc: 'Warnings and announcements from your teachers will appear here.', markAllRead: 'Mark all read', enablePush: 'Turn on notifications', pushOn: 'Notifications are on for this device.', pushDenied: 'Notifications are blocked in your browser settings.', pushUnsupported: 'This browser does not support notifications.', pushIosHint: 'On iPhone: open this site in Safari → Share → Add to Home Screen, then open it from the Home Screen and turn notifications on.', pushFail: 'Could not turn on notifications.',
  /* teacher */
  coursesDesc: 'Courses you teach this term.', students_: 'Students', lecturesN: 'Lectures', lastLecture: 'Last lecture', newLecture: 'New lecture', open: 'Open', lectureDate: 'Date', topic: 'Topic (optional)', remindShort: 'Warn students below minimum', remindDone: 'Warnings sent', shortageN: 'Below minimum', noLectures: 'No lectures yet', noLecturesDesc: 'Start a lecture to mark attendance.', pending: 'Waiting to sync', synced: 'All saved', saveOffline: 'No connection. Saved on this device and will sync automatically.', saveOk: 'Attendance saved', unmarkedWarn: 'Some students are unmarked.', deleteLecture: 'Delete this lecture and its attendance?',
  codeCheckin: 'Code check-in', openCheckin: 'Open check-in', closeCheckin: 'Close', minutes: 'Open for (minutes)', useLocation: 'Only allow students inside the classroom (uses your location)', radius: 'Radius (metres)', codeNow: 'Show this code to the class', checkedInN: 'checked in', expiresIn: 'changes in', checkinClosed: 'Check-in is closed.', gettingLocation: 'Getting your location…',
  /* hod / admin */
  deptOverview: 'Department overview', attendanceRate: 'Attendance rate', lectures: 'Lectures', shortageList: 'Students below the minimum', exportCsv: 'Export CSV', noShortage: 'Nobody is below the minimum.', whatsapp: 'WhatsApp', section: 'Section', enrolled: 'Enrolled', rate: 'Rate',
  adminHome: 'System overview', usersN: 'Users', studentsN: 'Students', offeringsN: 'Course offerings', sessionsN: 'Lectures', recordsN: 'Attendance records', pushSubs: 'Devices with notifications', lastBackup: 'Last backup', runBackup: 'Back up now', backupDone: 'Backup completed', noBackupDir: 'Backups are not configured on this server (GMC_BACKUP_DIR).', dbSize: 'Database size', never: 'Never',
  structure: 'Academic structure', departments: 'Departments', programs: 'Programs', terms: 'Terms', sections: 'Sections', coursesT: 'Courses', offerings: 'Offerings', add: 'Add', edit: 'Edit', del: 'Delete', code: 'Code', name: 'Name', dept: 'Department', program: 'Program', term: 'Term', teacher: 'Teacher', minPct: 'Minimum % (optional)', room: 'Room', days: 'Days', startTime: 'Start time', semNo: 'Semester no.', credits: 'Credits', starts: 'Starts', ends: 'Ends', active: 'Active',
  confirmDel: 'Delete this item? It cannot be undone.', inUse: 'This item is still in use or a referenced item is missing.', saved: 'Saved', deleted: 'Deleted',
  users: 'Users', addUser: 'Add user', role: 'Role', email: 'Email', phone: 'Phone', resetPw: 'Reset password', deactivate: 'Deactivate', activate: 'Activate', oneTimePw: 'One-time password', oneTimePwDesc: 'Copy it now: it is shown only once. The user must change it at first sign-in.', copy: 'Copy', copied: 'Copied', close: 'Close', allRoles: 'All roles', lastLogin: 'Last sign-in',
  studentsAdmin: 'Students', addStudent: 'Add student', importStudents: 'Import students', chooseFile: 'Choose a CSV or Excel file (columns: Roll, Name, Phone, optional Section)', defaultSection: 'Put students in section', importResult: 'Import finished', created: 'Created', updated: 'Updated', errors: 'Errors', createLogins: 'Create logins', loginsDone: 'Logins created', credentials: 'Credentials (shown once)', downloadCsv: 'Download CSV', print: 'Print', noSection: 'No section', hasLogin: 'Login', status: 'Status', roll: 'Roll no.', loginsHint: 'Create logins for one section at a time (up to 500 per click).',
  auditLog: 'Audit log', when: 'When', who: 'Who', action: 'Action', detail: 'Detail', loadMore: 'Load more', settingsTitle: 'Attendance rules', minAtt: 'Minimum attendance %', warnAt: 'Warning threshold %', leaveCounts: 'Count leave as present', lateCounts: 'Count late as present',
  language: 'Language', signedInAs: 'Signed in as', announce: 'Send announcement', announceTitle: 'Title', announceBody: 'Message', announceScope: 'Send to', scopeAll: 'Everyone', scopeDept: 'A department', scopeSection: 'A section', sentTo: 'Sent to', recipients: 'recipients'
});
Object.assign(I18N.ur, {
  offlineMsg: 'آپ آف لائن ہیں۔', busyRetry: 'سرور مصروف ہے۔ دوبارہ کوشش ہو رہی ہے…', loadFailed: 'یہ صفحہ لوڈ نہیں ہو سکا', loadFailedDesc: 'انٹرنیٹ چیک کر کے دوبارہ کوشش کریں۔', sessionExpired: 'آپ کا سیشن ختم ہو گیا۔ دوبارہ لاگ اِن کریں۔', gettingLocation: 'آپ کی لوکیشن لی جا رہی ہے…', announceScope: 'کس کو بھیجنا ہے', students_: 'طلبہ', whatsapp: 'واٹس ایپ', pushSubs: 'اطلاعات والے ڈیوائسز', dbSize: 'ڈیٹابیس کا سائز', noBackupDir: 'اس سرور پر بیک اپ سیٹ نہیں (GMC_BACKUP_DIR)۔',
  starts: 'آغاز', ends: 'اختتام', semNo: 'سمسٹر نمبر', credits: 'کریڈٹ', minPct: 'کم از کم % (اختیاری)', days: 'دن', inUse: 'یہ چیز ابھی استعمال میں ہے یا متعلقہ چیز موجود نہیں۔', chooseFile: 'CSV یا ایکسل فائل چنیں (کالم: رول، نام، فون)', defaultSection: 'طلبہ کو اس سیکشن میں رکھیں', noSection: 'کوئی سیکشن نہیں', importResult: 'امپورٹ مکمل', created: 'نئے', updated: 'اپ ڈیٹ', errors: 'غلطیاں', loginsHint: 'ایک وقت میں ایک سیکشن کے لاگ اِن بنائیں (ایک کلک پر زیادہ سے زیادہ 500)۔', hasLogin: 'لاگ اِن', allRoles: 'تمام کردار', lastLogin: 'آخری لاگ اِن', detail: 'تفصیل',
  outNeed: 'کم از کم حد تک پہنچنے کے لیے اگلے {n} لیکچرز میں حاضر ہوں', outSpare: 'آپ مزید {n} لیکچرز چھوڑ سکتے ہیں', remindAsk: '{n} طلبہ کم از کم حد سے نیچے ہیں۔ انہیں تنبیہی اطلاع بھیجیں؟', waText: 'السلام علیکم {name}، {course} میں آپ کی حاضری {pct} ہے (کم از کم {min}%)۔ براہِ کرم باقاعدگی سے آئیں۔', delLectureBtn: 'لیکچر حذف کریں', noData: 'ابھی ڈیٹا نہیں',
  pTitle: 'جی ایم سی چیک اِن', signIn: 'لاگ اِن', signOut: 'لاگ آؤٹ', loginId: 'ای میل یا رول نمبر', password: 'پاس ورڈ', loginHint: 'طلبہ اپنے رول نمبر سے لاگ اِن کریں۔',
  mustChangeTitle: 'نیا پاس ورڈ چنیں', mustChangeDesc: 'آپ کی حفاظت کے لیے آگے بڑھنے سے پہلے اپنا پاس ورڈ بنانا ضروری ہے۔', currentPw: 'موجودہ پاس ورڈ', newPw: 'نیا پاس ورڈ (کم از کم 10 حروف)', confirmPw: 'نیا پاس ورڈ دوبارہ لکھیں', pwMismatch: 'دونوں پاس ورڈ ایک جیسے نہیں۔', savePw: 'پاس ورڈ محفوظ کریں',
  nHome: 'ہوم', nInbox: 'ان باکس', nCourses: 'میرے کورسز', nDept: 'شعبہ', nOverview: 'جائزہ', nStructure: 'ڈھانچہ', nStudents: 'طلبہ', nUsers: 'صارفین', nAudit: 'آڈٹ لاگ', nSettings: 'سیٹنگز', nAllCourses: 'کورسز',
  myAttendance: 'میری حاضری', overall: 'مجموعی', courses: 'کورسز', course: 'کورس', recentRecords: 'حالیہ ریکارڈ', checkinOpen: 'چیک اِن کھلا ہے', enterCode: 'استاد کا دکھایا ہوا 6 ہندسوں کا کوڈ لکھیں', checkIn: 'چیک اِن', checkedIn: 'آپ کی حاضری لگ گئی۔', alreadyMarked: 'اس لیکچر کی حاضری پہلے ہی لگ چکی ہے۔', needLocation: 'اس لیکچر کے لیے آپ کی لوکیشن درکار ہے۔ لوکیشن کی اجازت دیں۔',
  locDenied: 'لوکیشن کی اجازت نہیں ملی۔', noEnrol: 'آپ ابھی کسی کورس میں داخل نہیں۔ دفتر سے سیکشن میں شامل کروائیں۔', noOpen: 'ابھی کوئی چیک اِن کھلا نہیں۔', lecturesHeld: 'ہو چکے لیکچرز', outlookLbl: 'امکان',
  inboxEmpty: 'ابھی کوئی اطلاع نہیں', inboxEmptyDesc: 'اساتذہ کی تنبیہات اور اعلانات یہاں نظر آئیں گے۔', markAllRead: 'سب پڑھے ہوئے', enablePush: 'اطلاعات آن کریں', pushOn: 'اس ڈیوائس پر اطلاعات آن ہیں۔', pushDenied: 'براؤزر کی سیٹنگز میں اطلاعات بلاک ہیں۔', pushUnsupported: 'یہ براؤزر اطلاعات کو سپورٹ نہیں کرتا۔', pushIosHint: 'آئی فون پر: سفاری میں یہ سائٹ کھولیں ← شیئر ← Add to Home Screen، پھر ہوم اسکرین سے کھول کر اطلاعات آن کریں۔', pushFail: 'اطلاعات آن نہیں ہو سکیں۔',
  coursesDesc: 'اس ٹرم میں آپ کے پڑھائے جانے والے کورسز۔', lecturesN: 'لیکچرز', lastLecture: 'آخری لیکچر', newLecture: 'نیا لیکچر', open: 'کھولیں', lectureDate: 'تاریخ', topic: 'موضوع (اختیاری)', remindShort: 'کم حاضری والوں کو تنبیہ', remindDone: 'تنبیہات بھیج دی گئیں', shortageN: 'کم از کم سے نیچے', noLectures: 'ابھی کوئی لیکچر نہیں', noLecturesDesc: 'حاضری لگانے کے لیے لیکچر شروع کریں۔', pending: 'سنک کا انتظار', synced: 'سب محفوظ', saveOffline: 'کنکشن نہیں۔ اس ڈیوائس پر محفوظ ہے اور خود سنک ہو جائے گا۔', saveOk: 'حاضری محفوظ ہو گئی',
  codeCheckin: 'کوڈ چیک اِن', openCheckin: 'چیک اِن کھولیں', closeCheckin: 'بند کریں', minutes: 'کتنے منٹ کھلا رہے', useLocation: 'صرف کلاس روم کے اندر والے طلبہ (آپ کی لوکیشن استعمال ہوگی)', radius: 'رداس (میٹر)', codeNow: 'یہ کوڈ کلاس کو دکھائیں', checkedInN: 'چیک اِن ہو چکے', expiresIn: 'بدلنے میں', checkinClosed: 'چیک اِن بند ہے۔',
  deptOverview: 'شعبے کا جائزہ', attendanceRate: 'حاضری کی شرح', lectures: 'لیکچرز', shortageList: 'کم از کم سے نیچے طلبہ', exportCsv: 'CSV ایکسپورٹ', noShortage: 'کوئی بھی کم از کم حد سے نیچے نہیں۔', section: 'سیکشن', enrolled: 'داخل طلبہ', rate: 'شرح',
  adminHome: 'سسٹم کا جائزہ', usersN: 'صارفین', studentsN: 'طلبہ', offeringsN: 'کورس آفرنگز', sessionsN: 'لیکچرز', recordsN: 'حاضری ریکارڈ', lastBackup: 'آخری بیک اپ', runBackup: 'ابھی بیک اپ لیں', backupDone: 'بیک اپ مکمل', never: 'کبھی نہیں',
  structure: 'تعلیمی ڈھانچہ', departments: 'شعبے', programs: 'پروگرام', terms: 'ٹرمز', sections: 'سیکشنز', coursesT: 'کورسز', offerings: 'آفرنگز', add: 'شامل', edit: 'ترمیم', del: 'حذف', code: 'کوڈ', name: 'نام', dept: 'شعبہ', program: 'پروگرام', term: 'ٹرم', teacher: 'استاد', room: 'کمرہ', active: 'فعال',
  confirmDel: 'کیا حذف کریں؟ یہ واپس نہیں ہو سکے گا۔', saved: 'محفوظ ہو گیا', deleted: 'حذف ہو گیا',
  users: 'صارفین', addUser: 'صارف شامل کریں', role: 'کردار', email: 'ای میل', phone: 'فون', resetPw: 'پاس ورڈ ری سیٹ', deactivate: 'غیر فعال', activate: 'فعال', oneTimePw: 'ایک بار کا پاس ورڈ', oneTimePwDesc: 'ابھی کاپی کر لیں: یہ صرف ایک بار دکھایا جاتا ہے۔ صارف کو پہلے لاگ اِن پر بدلنا ہوگا۔', copy: 'کاپی', copied: 'کاپی ہو گیا', close: 'بند کریں',
  studentsAdmin: 'طلبہ', addStudent: 'طالب علم شامل کریں', importStudents: 'طلبہ امپورٹ', createLogins: 'لاگ اِن بنائیں', loginsDone: 'لاگ اِن بن گئے', credentials: 'لاگ اِن تفصیل (ایک بار)', downloadCsv: 'CSV ڈاؤن لوڈ', print: 'پرنٹ', roll: 'رول نمبر',
  auditLog: 'آڈٹ لاگ', when: 'کب', who: 'کس نے', action: 'عمل', loadMore: 'مزید', settingsTitle: 'حاضری کے اصول', minAtt: 'کم از کم حاضری %', warnAt: 'انتباہ کی حد %', leaveCounts: 'رخصت کو حاضر شمار کریں', lateCounts: 'دیر سے آنے کو حاضر شمار کریں',
  language: 'زبان', signedInAs: 'لاگ اِن بطور', announce: 'اعلان بھیجیں', announceTitle: 'عنوان', announceBody: 'پیغام', scopeAll: 'سب کو', scopeDept: 'کسی شعبے کو', scopeSection: 'کسی سیکشن کو', sentTo: 'بھیجا گیا', recipients: 'وصول کنندگان'
});
